// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/healthcheck.proto

/*
Package healthcheck is a generated protocol buffer package.

It is generated from these files:
	proto/healthcheck.proto

It has these top-level messages:
	Request
	Response
	EmptyRequest
	EmptyResponse
*/
package healthcheck

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Ethealth service

type EthealthService interface {
	Check(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type ethealthService struct {
	c    client.Client
	name string
}

func NewEthealthService(name string, c client.Client) EthealthService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "ethealth"
	}
	return &ethealthService{
		c:    c,
		name: name,
	}
}

func (c *ethealthService) Check(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Ethealth.Check", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Ethealth service

type EthealthHandler interface {
	Check(context.Context, *Request, *Response) error
}

func RegisterEthealthHandler(s server.Server, hdlr EthealthHandler, opts ...server.HandlerOption) error {
	type ethealth interface {
		Check(ctx context.Context, in *Request, out *Response) error
	}
	type Ethealth struct {
		ethealth
	}
	h := &ethealthHandler{hdlr}
	return s.Handle(s.NewHandler(&Ethealth{h}, opts...))
}

type ethealthHandler struct {
	EthealthHandler
}

func (h *ethealthHandler) Check(ctx context.Context, in *Request, out *Response) error {
	return h.EthealthHandler.Check(ctx, in, out)
}

// Client API for Foo service

type FooService interface {
	Bar(ctx context.Context, in *EmptyRequest, opts ...client.CallOption) (*EmptyResponse, error)
}

type fooService struct {
	c    client.Client
	name string
}

func NewFooService(name string, c client.Client) FooService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "foo"
	}
	return &fooService{
		c:    c,
		name: name,
	}
}

func (c *fooService) Bar(ctx context.Context, in *EmptyRequest, opts ...client.CallOption) (*EmptyResponse, error) {
	req := c.c.NewRequest(c.name, "Foo.Bar", in)
	out := new(EmptyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Foo service

type FooHandler interface {
	Bar(context.Context, *EmptyRequest, *EmptyResponse) error
}

func RegisterFooHandler(s server.Server, hdlr FooHandler, opts ...server.HandlerOption) error {
	type foo interface {
		Bar(ctx context.Context, in *EmptyRequest, out *EmptyResponse) error
	}
	type Foo struct {
		foo
	}
	h := &fooHandler{hdlr}
	return s.Handle(s.NewHandler(&Foo{h}, opts...))
}

type fooHandler struct {
	FooHandler
}

func (h *fooHandler) Bar(ctx context.Context, in *EmptyRequest, out *EmptyResponse) error {
	return h.FooHandler.Bar(ctx, in, out)
}
